/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardVetRouteImport } from './routes/dashboard.vet'
import { Route as DashboardMarketplaceRouteImport } from './routes/dashboard.marketplace'
import { Route as DashboardListingsRouteImport } from './routes/dashboard.listings'
import { Route as DashboardFinancialRouteImport } from './routes/dashboard.financial'
import { Route as DashboardConsultationsRouteImport } from './routes/dashboard.consultations'
import { Route as DashboardAdminRouteImport } from './routes/dashboard.admin'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardVetRoute = DashboardVetRouteImport.update({
  id: '/vet',
  path: '/vet',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMarketplaceRoute = DashboardMarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardListingsRoute = DashboardListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFinancialRoute = DashboardFinancialRouteImport.update({
  id: '/financial',
  path: '/financial',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardConsultationsRoute = DashboardConsultationsRouteImport.update({
  id: '/consultations',
  path: '/consultations',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/consultations': typeof DashboardConsultationsRoute
  '/dashboard/financial': typeof DashboardFinancialRoute
  '/dashboard/listings': typeof DashboardListingsRoute
  '/dashboard/marketplace': typeof DashboardMarketplaceRoute
  '/dashboard/vet': typeof DashboardVetRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/consultations': typeof DashboardConsultationsRoute
  '/dashboard/financial': typeof DashboardFinancialRoute
  '/dashboard/listings': typeof DashboardListingsRoute
  '/dashboard/marketplace': typeof DashboardMarketplaceRoute
  '/dashboard/vet': typeof DashboardVetRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/consultations': typeof DashboardConsultationsRoute
  '/dashboard/financial': typeof DashboardFinancialRoute
  '/dashboard/listings': typeof DashboardListingsRoute
  '/dashboard/marketplace': typeof DashboardMarketplaceRoute
  '/dashboard/vet': typeof DashboardVetRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/dashboard/admin'
    | '/dashboard/consultations'
    | '/dashboard/financial'
    | '/dashboard/listings'
    | '/dashboard/marketplace'
    | '/dashboard/vet'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard/admin'
    | '/dashboard/consultations'
    | '/dashboard/financial'
    | '/dashboard/listings'
    | '/dashboard/marketplace'
    | '/dashboard/vet'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/dashboard/admin'
    | '/dashboard/consultations'
    | '/dashboard/financial'
    | '/dashboard/listings'
    | '/dashboard/marketplace'
    | '/dashboard/vet'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/vet': {
      id: '/dashboard/vet'
      path: '/vet'
      fullPath: '/dashboard/vet'
      preLoaderRoute: typeof DashboardVetRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/marketplace': {
      id: '/dashboard/marketplace'
      path: '/marketplace'
      fullPath: '/dashboard/marketplace'
      preLoaderRoute: typeof DashboardMarketplaceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/listings': {
      id: '/dashboard/listings'
      path: '/listings'
      fullPath: '/dashboard/listings'
      preLoaderRoute: typeof DashboardListingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/financial': {
      id: '/dashboard/financial'
      path: '/financial'
      fullPath: '/dashboard/financial'
      preLoaderRoute: typeof DashboardFinancialRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/consultations': {
      id: '/dashboard/consultations'
      path: '/consultations'
      fullPath: '/dashboard/consultations'
      preLoaderRoute: typeof DashboardConsultationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardConsultationsRoute: typeof DashboardConsultationsRoute
  DashboardFinancialRoute: typeof DashboardFinancialRoute
  DashboardListingsRoute: typeof DashboardListingsRoute
  DashboardMarketplaceRoute: typeof DashboardMarketplaceRoute
  DashboardVetRoute: typeof DashboardVetRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardConsultationsRoute: DashboardConsultationsRoute,
  DashboardFinancialRoute: DashboardFinancialRoute,
  DashboardListingsRoute: DashboardListingsRoute,
  DashboardMarketplaceRoute: DashboardMarketplaceRoute,
  DashboardVetRoute: DashboardVetRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
